# Generated by Django 2.2.3 on 2019-07-24 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tweetNsellServer.API.models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_administrator_brand_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='id',
        ),
        migrations.AlterField(
            model_name='administrator',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='service_industry',
            field=models.ForeignKey(default=tweetNsellServer.API.models.Brand.default_service_industry, on_delete=django.db.models.deletion.SET_DEFAULT, to='API.ServiceIndustry'),
        ),
    ]
