# Generated by Django 2.2.3 on 2019-07-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20190724_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceindustry',
            options={'verbose_name': 'Service Industry', 'verbose_name_plural': 'Service Industries'},
        ),
    ]
