# Generated by Django 2.2.3 on 2019-07-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20190724_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='attitude',
            field=models.CharField(choices=[('pos', 'Positive'), ('neg', 'Negative'), ('neu', 'Neutral'), ('unc', 'Uncategorized')], default='unc', max_length=3),
        ),
        migrations.AlterField(
            model_name='serviceindustry',
            name='name_en',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceindustry',
            name='name_es',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
