# Generated by Django 2.2.3 on 2019-07-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20190724_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('number_followers', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='opinion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Customer'),
        ),
    ]
