# Generated by Django 2.2.3 on 2019-07-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20190726_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Customer'),
        ),
    ]
