# Generated by Django 2.2.3 on 2019-07-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20190726_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='number_new_opinions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
