# Generated by Django 2.2.3 on 2019-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_remove_brand_are_all_opinions_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='followers_cursor',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='brand',
            name='last_followers_load_moment',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='number_new_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=60)),
                ('number_tweets', models.PositiveIntegerField()),
                ('number_followers', models.PositiveIntegerField()),
                ('number_friends', models.PositiveIntegerField()),
                ('influence', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('brands', models.ManyToManyField(to='API.Brand')),
            ],
        ),
    ]
