# Generated by Django 2.2.3 on 2019-07-31 10:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20190730_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='last_followers_load_moment',
        ),
        migrations.AddField(
            model_name='follower',
            name='k',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='follower',
            name='k_retweets',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='k_tweet_publication_moment',
            field=models.DateTimeField(null=True),
        ),
    ]
