# Generated by Django 2.2.3 on 2019-07-31 10:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20190731_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='k',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='follower',
            name='k_retweets',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='follower',
            name='k_tweet_publication_moment',
            field=models.DateTimeField(),
        ),
    ]
