# Generated by Django 2.2.3 on 2019-08-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20190731_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='number_friends',
        ),
    ]
