# Generated by Django 2.2.3 on 2019-08-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_remove_follower_number_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='influence',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
