# Generated by Django 2.2.3 on 2019-08-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_auto_20190801_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='opinions_cursor',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='opinion',
            name='preprocessed_text',
            field=models.TextField(blank=True),
        ),
    ]
